name: Build and deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: Build and export the Next.js project
        run: yarn && yarn build

      - name: Deploy to Firebase Hosting
        run: yarn add firebase-tools && yarn run firebase deploy -m "$MESSAGE"
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

