name: Build and deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build and export the Next.js project
        run: yarn build

      - name: Install Firebase CLI
        run: yarn global add firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --message='${{ github.event.head_commit.message }}'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
