name: Build and deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy to Firebase Hosting
    runs-on: ubuntu-latest
    steps:

      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install

      - name: ⚙️ Build and export the Next.js project
        run: yarn build

      - name: 🏗 Install Firebase CLI
        run: yarn global add firebase-tools

      - name: 🔑 Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 🚀 Deploy to Firebase Hosting
        run: firebase deploy --message='${{ github.event.head_commit.message }}'
